### ISSUE TITLE
When no error, the NULL is stored as a string

### ISSUE THREAD

**Issue by pietos** [daycry/cronjob#12]
File: app\ThirdParty\vendor\daycry\cronjob\src\JobRunner.php
Line: 188

The null is wrapped in the json_encode, which results in the database that the value is not stored as NULL but as "null".

![image](https://user-images.githubusercontent.com/58322436/235921314-3a6a8751-f99a-49f0-a008-43814642e083.png)

**Comment by pietos** [comment]
This is my solution for now:

'error'    => $jobLog->error? json_encode($jobLog->error) : NULL,

**Comment by daycry** [comment]
I fix it in **v.2.2.8** version

**Comment by daycry** [comment]
Fixed
