### ISSUE TITLE
I'd like to be able to protect the dashboard

### ISSUE THREAD

**Issue by SvetoslavStefanov** [daycry/cronjob#16]
Hey,
Thank you for this awesome package, I love it!

Is there a possibility to add the ability to vednor publish the View files? I'd like to be able to edit them. I'd like to put a button there to disable all cron jobs, just in case (I was having problems with sending bulk emails, and the script was stuck and was sending the same email over and over again to the same people. I'd like to have some GUI where I could stop this from my phone while I'm out).

Also, it would be very helpful if I could protect the dashboard to be accessible only by Admin users.

EDIT:
I figure it out. It's just not described in the Readme file. For everybody else encountering this issue: 
Go to app\Config\CronJob.php ->views['dashboard'] and put your view's path there, like: "Cronjob/dashboard" - which is located in `app\Views\Cronjob\dashboard.php`

EDIT2:
nvm, I found a way to overrule the dashboard.
`$routes->get('cronjob/dashboard', [\Daycry\CronJob\Controllers\Dashboard::class, 'index'], ['filter' => 'your_filter_where_you_could_stop_the_request']);`

**Comment by maheshwari-vaibhav** [comment]
@daycry can you please explain me what you need here

**Comment by daycry** [comment]
Hi!

If you want contribute in this project doing this changes I would appreciate it.

Also, Dashboard is protected by user and pass, this is a very simple solution but works it, althouth using a filter is very elegant.

Thanks for your help.

**Comment by adeelmughal4u** [comment]
I am not able to load url.com/cronjob

I checked everything and all okay but still not able to load it.
