### ISSUE TITLE
Starting scheduler (system cron issue)

### ISSUE THREAD

**Issue by pietos** [daycry/cronjob#18]
In your example you define the cronjob as follows:

* * * * * cd /path-to-your-project && php spark cronjob:run >> /dev/null 2>&1

I tried to implement this in a docker project where the docker was running Debian.
Unfortunately Debian didn't accept a cd with a command after it, what did work for me was the following:

* * * * * php /path-to-your-project/spark cronjob:run >> /dev/null 2>&1

**Comment by daycry** [comment]
You can use this:

php /path-to-your-project/spark cronjob:run >> /dev/null 2>&1

**Comment by pietos** [comment]
That's what I mentioned right? My suggestion is to update your readme with with answer.
