### ISSUE TITLE
Week days cron example is incorrect

### ISSUE THREAD

**Issue by pietos** [daycry/cronjob#19]
In your example you define:

->sundays('3:15 am') | Runs every Sunday at midnight, unless time passed in.
->mondays('3:15 am') | Runs every Monday at midnight, unless time passed in.
->tuesdays('3:15 am') | Runs every Tuesday at midnight, unless time passed in.
->wednesdays('3:15 am') | Runs every Wednesday at midnight, unless time passed in.
->thursdays('3:15 am') | Runs every Thursday at midnight, unless time passed in.
->fridays('3:15 am') | Runs every Friday at midnight, unless time passed in.
->saturdays('3:15 am') | Runs every Saturday at midnight, unless time passed in.

But when you call for example ->saturdays() without a time, it will not run at midnight, it will run every minute on saturday.
 Clean Device Finder          | shell   | * * * * 6    | 2023-07-15 10:08:06 | 2023-07-15 10:09:00 

![image](https://github.com/daycry/cronjob/assets/58322436/a683f61e-2e1c-4db3-bfc9-27267fff6391)

**Comment by daycry** [comment]
I will check this issue

**Comment by daycry** [comment]
Fixed in [V2.2.13](https://github.com/daycry/cronjob/releases/tag/V2.2.13)
