### ISSUE TITLE
CI_ENVIRONMENT

### ISSUE THREAD

**Issue by andrewice77** [daycry/cronjob#27]
When run cronjob:run :(

**** Running Tasks... ****

[ErrorException]

Undefined array key "CI_ENVIRONMENT"

at VENDORPATH/daycry/cronjob/src/Traits/ActivityTrait.php:28

**Comment by daycry** [comment]
What version of CodeIgniter 4 do you have?

Do you have the following configured in the .env file?

#--------------------------------------------------------------------
# ENVIRONMENT
#--------------------------------------------------------------------

CI_ENVIRONMENT = development

**Comment by andrewice77** [comment]
I am using CodeIgniter 4 version 4.4.5. In the production environment, I don't utilize the .env file. Everything functions properly in the development environment.

I've noticed that "url" type cron jobs are not being executed correctly.

**Comment by andrewice77** [comment]
Correggimi questo inglese
I have 4.4.5 version and the .env file is not used because I'm in a production environment.
In development everything works. 

Also when I insert "url" type cron that are not executed.

**Comment by andrewice77** [comment]
`if (!empty($this->environments) && ! $this->runsInEnvironment($_SERVER['CI_ENVIRONMENT'])) {
            return false;
        }`
Why do you use $_SERVER['CI_ENVIRONMENT']? 
You have a constant CI_ENVIRONMENT

**Comment by daycry** [comment]
You can set this constant environment in production environment.
I use that constant to know the environment in which jobs are running.
It's a constant in the framework.

**Comment by andrewice77** [comment]
It's already set up but the error it's still here. :(

**Comment by andrewice77** [comment]
For now I removed "environments" in init method configuration.
