### ISSUE TITLE
ERROR - daycry/cronjob/src/Traits/ActivityTrait.php - setting()

### ISSUE THREAD

**Issue by rodrigoinco** [daycry/cronjob#29]
I got this error, when access the dashboard:

Error

Call to undefined function Daycry\CronJob\Traits\setting()

VENDORPATH/daycry/cronjob/src/Traits/ActivityTrait.php at line 46

Until, last week it was working, but starts to show this error, now.

**Comment by daycry** [comment]
Try to update to v2.2.23.
