### ISSUE TITLE
Cannot access protected property

### ISSUE THREAD

**Issue by aradono** [daycry/cronjob#30]
Hi,

All is working perfectly but I can't see jobs list on dashboard page.
When I go to the dashboard page, i've got an error : "Cannot access protected property Daycry\CronJob\Job::$name"
VENDORPATH\daycry\cronjob\src\Views\dashboard.php at line 28

`<td><?= $job->name ?></td>`

If I delete all $job->name in the view, it's working. The error seems be related to the variable "name".
My install is up to date with composer.

Thank you for your help !

**Comment by daycry** [comment]
Hello,

Try update yo v2.2.24.

Thank you
