### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by markatsdp** [daycry/cronjob#36]
Hi, I get an error saying: array_key_exists(): Argument #2 ($array) must be of type array, null given 

VENDORPATH/daycry/cronjob/src/Traits/LogTrait.php at line 88:
if(!setting('CronJob.logSavingMethod') || !array_key_exists(setting('CronJob.logSavingMethod'), setting('CronJob.logSavingMethodClassMap'))) {
throw CronJobException::forInvalidLogType();
}

---
It seems like setting('CronJob.logSavingMethodClassMap') is not defined properly. Any tips?

**Comment by markatsdp** [comment]
In the meantime, I just added these in the Config/CronJjob.php for now:

use Daycry\CronJob\Loggers\Database as DatabaseLogger;
use Daycry\CronJob\Loggers\File as FileLogger;

public array $logSavingMethodClassMap = [
        'file' => FileLogger::class,
        'database' => DatabaseLogger::class
    ];

**Comment by daycry** [comment]
Hi!

In cronjob file config you can the this array
