### ISSUE TITLE
Cron command args

### ISSUE THREAD

**Issue by andrewice77** [daycry/cronjob#37]
When a cron "command" is executed, the arguments passed within it are not considered. For example:
flows:execute -run
"run" is not included within the command.

**Comment by daycry** [comment]
You might be doing something wrong because I use it without problems.

send me a screenshot of your code

**Comment by andrewice77** [comment]
Here is a cron from backend. 
![Schermata del 2024-05-25 18-54-24](https://github.com/daycry/cronjob/assets/25518899/b3f129fe-5a52-48ef-afd6-cf76e5f67361)

This is code when command is executed. 
There is a test for print options passed from command line
![Schermata del 2024-05-25 18-48-30](https://github.com/daycry/cronjob/assets/25518899/b73a5bcb-3cf6-4ecd-8449-cbabf1704c19)

This is output from command line when run cron and test of command.
![Schermata del 2024-05-25 18-57-18](https://github.com/daycry/cronjob/assets/25518899/848aa07a-3804-4a24-8ffe-14ab6dfdbcb3)

**Comment by andrewice77** [comment]
Ok I fixed. 
I'm sorry.... 😄
