### ISSUE TITLE
Class 'Cron\CronExpression' not found

### ISSUE THREAD

**Issue by jadsy2107** [daycry/cronjob#6]
I followed your steps, namely:

Downloaded and unzip to ThirdParty/ 

the psr4 added:

        'Daycry\CronJob' => APPPATH .'ThirdParty/cronjob/src'

But I get error when i run this command: 
php spark cronjob:list

Class 'Cron\CronExpression' not found

**Comment by jadsy2107** [comment]
i fixed it, had to run compose require command in root of project

**Comment by jadsy2107** [comment]
Now I have an issue with url cronJob .. its not working? 
Does it check server certificate ?

**Comment by jadsy2107** [comment]
> Now I have an issue with url cronJob .. its not working? Does it check server certificate ?

Again fixed the issue, my hosting server ca was not up to date. curl request was failing, fixed! 
Please close this issue, great project thank you.!

**Comment by jadsy2107** [comment]
Ok, so far this is the only issue remaining which I think is a bug, The cronjob log shows duration of 3 minutes, when in fact it ran for 3 seconds, see below: 

2022-06-13 16:45:01 | 2022-06-13 16:45:04 | 00:03:00

Set to log to database

**Comment by jadsy2107** [comment]
Also, cronjob log 'output' field is always empty, even though my scheduled command returns data.

**Comment by pietos** [comment]
> I followed your steps, namely:
> 
> Downloaded and unzip to ThirdParty/
> 
> the psr4 added:
> 
> ```
>     'Daycry\CronJob' => APPPATH .'ThirdParty/cronjob/src'
> ```
> 
> But I get error when i run this command: php spark cronjob:list
> 
> Class 'Cron\CronExpression' not found

I had the same, you don't have to run the composer in the root, solution is to update ci4 to the latest version and make sure you overwrite your spark file

**Comment by daycry** [comment]
I recommended install this vendor with composer, because you need
CronExpression library. Or install it manually downloading like cronjob
vendor.
